create table if not exists public.email_verification_codes (
    id bigint generated by default as identity primary key,
    email text not null,
    purpose text not null default 'password_reset',
    code_hash text not null,
    expires_at timestamptz not null,
    used_at timestamptz,
    created_at timestamptz not null default now()
);

create index if not exists idx_email_verification_codes_lookup
    on public.email_verification_codes (email, purpose, created_at desc);

alter table public.email_verification_codes enable row level security;

drop policy if exists "service role only email verification codes" on public.email_verification_codes;
create policy "service role only email verification codes"
    on public.email_verification_codes
    for all
    using (auth.role() = 'service_role')
    with check (auth.role() = 'service_role');
