create table if not exists public.oferta_conversaciones (
    id_conversacion bigint generated by default as identity primary key,
    id_producto int4 not null references public.productos(id_producto) on delete cascade,
    nombre_producto text not null,
    precio_base numeric not null,
    foto_url text,
    id_comprador int4 not null references public.usuarios(id_usuario) on delete cascade,
    nombre_comprador text not null,
    id_vendedor int4 not null references public.usuarios(id_usuario) on delete cascade,
    nombre_vendedor text not null,
    created_at bigint not null default ((extract(epoch from now()) * 1000)::bigint),
    updated_at bigint not null default ((extract(epoch from now()) * 1000)::bigint),
    unique (id_producto, id_comprador, id_vendedor)
);

create index if not exists idx_oferta_conversaciones_comprador
    on public.oferta_conversaciones (id_comprador, updated_at desc);

create index if not exists idx_oferta_conversaciones_vendedor
    on public.oferta_conversaciones (id_vendedor, updated_at desc);

create table if not exists public.oferta_mensajes (
    id_oferta bigint generated by default as identity primary key,
    id_conversacion bigint not null references public.oferta_conversaciones(id_conversacion) on delete cascade,
    id_comprador int4 not null references public.usuarios(id_usuario) on delete cascade,
    importe numeric not null,
    estado text not null default 'PENDING' check (estado in ('PENDING', 'ACCEPTED', 'REJECTED')),
    created_at bigint not null default ((extract(epoch from now()) * 1000)::bigint)
);

create index if not exists idx_oferta_mensajes_conversacion
    on public.oferta_mensajes (id_conversacion, created_at asc);

alter table public.oferta_conversaciones disable row level security;
alter table public.oferta_mensajes disable row level security;
